// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class Company
    {
        public Company()
        {
            Project = new HashSet<Project>();
            WorkflowStep = new HashSet<WorkflowStep>();
        }

        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNumber { get; set; }
        public DateTime? ChangedDateTime { get; set; }
        public long? ChangedBy { get; set; }
        public int CompanyType { get; set; }

        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<WorkflowStep> WorkflowStep { get; set; }
    }
}