// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class ModelSyncedDateTime
    {
        public string Model { get; set; }
        public DateTime LastSyncedDateTime { get; set; }
    }
}