// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class Project
    {
        public Project()
        {
            Phase = new HashSet<Phase>();
            WorkflowStep = new HashSet<WorkflowStep>();
        }

        public int ProjectId { get; set; }
        public int ProjectType { get; set; }
        public double? ActualBilledHours { get; set; }
        public double? ActualHours { get; set; }
        public int CompanyId { get; set; }
        public string Description { get; set; }
        public double? EstimatedTime { get; set; }
        public string ProjectName { get; set; }
        public string ProjectNumber { get; set; }
        public DateTime StartDateTime { get; set; }
        public DateTime EndDateTime { get; set; }
        public DateTime? LastActivityDateTime { get; set; }
        public int? ChangedBy { get; set; }
        public int? Status { get; set; }

        public virtual Company Company { get; set; }
        public virtual ICollection<Phase> Phase { get; set; }
        public virtual ICollection<WorkflowStep> WorkflowStep { get; set; }
    }
}