// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class Queue
    {
        public Queue()
        {
            TeamMemberRole = new HashSet<TeamMemberRole>();
            WorkflowStep = new HashSet<WorkflowStep>();
        }

        public int QueueId { get; set; }
        public string QueueName { get; set; }
        public bool? IsActive { get; set; }
        public int SortOrder { get; set; }

        public virtual ICollection<TeamMemberRole> TeamMemberRole { get; set; }
        public virtual ICollection<WorkflowStep> WorkflowStep { get; set; }
    }
}