// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class ScrumStatus
    {
        public ScrumStatus()
        {
            AutoTaskStatus = new HashSet<AutoTaskStatus>();
        }

        public int ScrumStatusId { get; set; }
        public string ScrumStatusText { get; set; }
        public int AutoTaskDefaultStatus { get; set; }

        public virtual AutoTaskStatus AutoTaskDefaultStatusNavigation { get; set; }
        public virtual ICollection<AutoTaskStatus> AutoTaskStatus { get; set; }
    }
}