// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class Sprint
    {
        public Sprint()
        {
            WorkflowStep = new HashSet<WorkflowStep>();
        }

        public int SprintId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool? Current { get; set; }

        public virtual ICollection<WorkflowStep> WorkflowStep { get; set; }
    }
}