// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class TeamMember
    {
        public TeamMember()
        {
            TeamMemberRole = new HashSet<TeamMemberRole>();
            WorkflowStep = new HashSet<WorkflowStep>();
            WorkflowStep2TeamMember = new HashSet<WorkflowStep2TeamMember>();
        }

        public int TeamMemberId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public bool? IsActive { get; set; }
        public string Title { get; set; }
        public string UserName { get; set; }
        public int? UserType { get; set; }
        public DateTime? ChangedDateTime { get; set; }
        public int? ChangedBy { get; set; }

        public virtual ICollection<TeamMemberRole> TeamMemberRole { get; set; }
        public virtual ICollection<WorkflowStep> WorkflowStep { get; set; }
        public virtual ICollection<WorkflowStep2TeamMember> WorkflowStep2TeamMember { get; set; }
    }
}