// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class TeamMemberRole
    {
        public long TeamMemberRoleId { get; set; }
        public int TeamMemberId { get; set; }
        public int RoleId { get; set; }
        public int? DepartmentId { get; set; }
        public int? QueueId { get; set; }
        public bool? IsActive { get; set; }

        public virtual Department Department { get; set; }
        public virtual Queue Queue { get; set; }
        public virtual Role Role { get; set; }
        public virtual TeamMember TeamMember { get; set; }
    }
}