// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class User
    {
        public string Email { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int? DepartmentId { get; set; }
        public int? QueueId { get; set; }
        public bool? IsDeveloper { get; set; }
        public bool? IsManager { get; set; }
    }
}