// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class UserFilter
    {
        public int FilterId { get; set; }
        public int UserId { get; set; }
        public string Entity { get; set; }
        public int? EntityId { get; set; }
    }
}