// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vision.Models
{
    public partial class WorkflowStep2TeamMember
    {
        public int WorkflowStepId { get; set; }
        public int TeamMemberId { get; set; }
        public int RoleId { get; set; }

        public virtual Role Role { get; set; }
        public virtual TeamMember TeamMember { get; set; }
        public virtual WorkflowStep WorkflowStep { get; set; }
    }
}